# Optional: GitHub Actions workflow for automatic deployment
# This file is commented out by default. To use it:
# 1. Remove the comments
# 2. Set up Firebase secrets in GitHub repository settings
# 3. Push to your repository

# name: Deploy to Firebase Hosting
# 
# on:
#   push:
#     branches:
#       - main
# 
# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#           
#       - name: Install dependencies
#         run: npm ci
#         
#       - name: Build
#         run: npm run build
#         env:
#           VITE_RAILWAY_API_URL: ${{ secrets.VITE_RAILWAY_API_URL }}
#           VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
#           VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
#           
#       - name: Deploy to Firebase
#         uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: '${{ secrets.GITHUB_TOKEN }}'
#           firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
#           channelId: live
#           projectId: aipply-website
